# Generated by Django 4.0.3 on 2022-03-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
